{% set name = "junitparser" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/junitparser-{{ version }}.tar.gz
  sha256: 9e053d7df3f425481a0e61fc2db99e348f14858af0390cc2e533006954b1cf15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - junitparser = junitparser.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    # used in setup.py
    - future
  run:
    - python >=3.6
    - future

test:
  imports:
    - junitparser
  commands:
    - pip check
    - junitparser --help
  requires:
    - pip

about:
  home: https://github.com/weiwei/junitparser
  summary: Manipulates JUnit/xUnit Result XML files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
