{% set name = "junitparser" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/junitparser-{{ version }}.tar.gz
  sha256: d5d07cece6d4a600ff3b7b96c8db5ffa45a91eed695cb86c45c3db113c1ca0f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - junitparser = junitparser.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=44
    - wheel >=0.37
    # used in setup.py
    - future
  run:
    - python >={{ python_min }}
    - future

test:
  imports:
    - junitparser
  commands:
    - pip check
    - junitparser --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/weiwei/junitparser
  summary: Manipulates JUnit/xUnit Result XML files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
