{% set name = "junitparser" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/junitparser-{{ version }}.tar.gz
  sha256: b05e89c27e7b74b3c563a078d6e055d95cf397444f8f689b0ca616ebda0b3c65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - junitparser = junitparser.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    # used in setup.py
    - future
  run:
    - python >={{ python_min }}
    - future

test:
  imports:
    - junitparser
  commands:
    - pip check
    - junitparser --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/weiwei/junitparser
  summary: Manipulates JUnit/xUnit Result XML files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
